AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-gemserver.gemspec"
    - "lib/google/cloud/**/*"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
    - "lib/patched/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ["class_eval"]
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Metrics/AbcSize:
  Max: 28
Metrics/MethodLength:
  Max: 22
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/CaseEquality:
  Enabled: false
